CC=gcc
CFLAGS=-g -Wall

TARGETS = gen-exe
OBJECTS = gen-exe.o

.PHONY: default
default: $(TARGETS)

$(TARGETS):

$(OBJECTS):

.PHONY: clean
clean:
	rm -f $(OBJECTS) $(TARGETS) a.out

.PHONY: all
all: clean default
